name = "cpac"
main = "worker/index.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cpac_booking_db"
database_id = "f9cd3d8d-4698-4698-aeb5-455b443f5ca3"
